services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: movie_picker_db
    networks:
      - movienet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=movie_db
      - MYSQL_USER=movie_picker_user
      - MYSQL_PASSWORD=${MOVIE_PICKER_DB_PASSWORD}
    volumes:
      - ./databases:/config
      - ./schema.sql:/config/initdb.d/schema.sql:ro
    restart: unless-stopped

  backend:
    build: ./app
    container_name: movie_picker_backend
    networks:
      - movienet
    env_file:
      - .env
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Copenhagen
      - MOVIE_PICKER_DB_PASSWORD=${MOVIE_PICKER_DB_PASSWORD}
      - TMDB_API_TOKEN=${TMDB_API_TOKEN}
    volumes:
      - ./app:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: movie_picker_frontend
    networks:
      - movienet
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx/.htpasswd:/etc/nginx/.htpasswd:ro

networks:
  movienet:
